/**
 * This file was generated by PlannerFw's Preprocessor
 * 
 * Version    0.0.1
 * Author     W3plan Technologies
 * Category   Preprocessor
 * Copyright  Copyright 2015-2016 W3plan Technologies, http://w3plan.net
 * Licenses   GNU GPLv3 license <http://www.gnu.org/copyleft/gpl.html>
 */
/* PlannerFw Template */
function pfTemp(pfDataSet, planner) {
var _pf19edb768 = '';_pf19edb768 += '<html lang="en"><head><meta charset="utf-8" /><meta name="description" content="demo" /><meta name="keywords" content="" /><title>Sample static page</title><link rel="stylesheet" type="text/css" href=\'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\' /><style> .mystyle { width: 800px; text-align:center; font-size:120%; } </style><script> var x = 5; var y = 6; var z = x + y; function myFunction() { document.getElementById("demo").innerHTML = "Paragraph changed!"; } </script></head><body><div class="mystyle"><div id="demo">Sample static page</div></div></body></html>';
return _pf19edb768;
}