/**
 * This file was generated by PlannerFw's Preprocessor
 * 
 * Version    0.0.1
 * Author     W3plan Technologies
 * Category   Preprocessor
 * Copyright  Copyright 2015-2016 W3plan Technologies, http://w3plan.net
 * Licenses   GNU GPLv3 license <http://www.gnu.org/copyleft/gpl.html>
 */
/* PlannerFw Template */
function pfTemp(pfDataSet, planner) {
var _pf19edb768 = '';_pf19edb768 += '<!DOCTYPE html><html><body><h2>My CD Collection</h2><table border="1"><tr bgcolor="#9acd32"><th style="text-align:left">Title</th><th style="text-align:left">Artist</th></tr> '; /* single line comment sample */ pfDataSet = pfDataSet.catalog; for(var key in pfDataSet.cd) {
_pf19edb768 += /* single line comment sample for output tag */ `<tr><td> ${pfDataSet.cd[key].title} </td><td> ${pfDataSet.cd[key].artist} </td></tr>`; }
_pf19edb768 += ' </table></body></html> ';
return _pf19edb768;
}